# Generated by Django 5.1.7 on 2025-04-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='one',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
