# Generated by Django 5.1.7 on 2025-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_one_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='one',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
