# Generated by Django 5.1.7 on 2025-04-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_one_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='one',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
