name: docker-project
services:

  app:
    build:
      context: .
      dockerfile: dockerfile
    image: docker-image
    container_name: docker-container
    ports:
     - "8000:8000"
    volumes:
      - .:/app  
      